version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/ragnet
      - JWT_SECRET=...
      - OPENAI_API_KEY=...
      # - DISCORD_BOT_TOKEN={DISCORD_BOT_TOKEN}
      # - DISCORD_CLIENT_ID={DISCORD_CLIENT_ID}
      # - DISCORD_CLIENT_SECRET={DISCORD_CLIENT_SECRET}
      # - DISCORD_REDIRECT_URI={DISCORD_REDIRECT_URI}
      - FRONTEND_URL=...
      - INGEST_DOCS=false
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=ragnet
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: ankane/pgvector:v0.5.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ragnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 